#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: ALM Autos cutover — GitHub Pages to Hetzner via Laravel Forge.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=13

# Values here get pasted into Forge's environment editor rather than read
# locally, so they stay out of the app's own .env.
ENV_FILE="${ENV_FILE:-.env.forge}"

banner "ALM Autos cutover"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Before you start"
say "This moves alm.autos from GitHub Pages to a Hetzner box managed by Forge."
say ""
warn "Three things here cannot be undone later. Each is called out as it arrives."
note "  - zero-downtime deploys can only be enabled when the site is created"
note "  - the uploads directory must sit outside releases/ from the first deploy"
note "  - the DNS switch is the visible one, and has a rollback (stage 13)"
say ""
say "You need, before starting:"
step "A Laravel Forge account with a subscription (SSL auto-renewal needs one)."
step "A Hetzner API token, or an existing Hetzner server to connect."
step "Login to whoever holds DNS for alm.autos."
step "A Resend account, or willingness to make one in stage 10."
say ""
if ! confirm "Do you have all four?"; then
  warn "Get those first. Re-run this when you do; nothing has changed yet."
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Provision the server"
open_url "https://forge.laravel.com/servers/create"
step "Provider: Hetzner. Server type: APP SERVER."
warn "A 'Web Server' cannot host a database. It must be an App Server."
step "Size: at least 4 GB RAM (CX22 or larger)."
note "Builds run in CI, but Postgres, Node and nginx share this box."
step "Database: PostgreSQL 17."
step "Provision, then wait for it to go green. This takes a few minutes."
say ""
warn "Forge shows the database passwords ONCE, on the completion screen."
ask SERVER_IP "Paste the server's public IP:"
ask_secret DB_PASSWORD "Paste the 'forge' database user password:"
write_env SERVER_IP "$SERVER_IP"
write_env DB_PASSWORD "$DB_PASSWORD"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Nginx template"
say "This app is Nitro-based. Forge's built-in Node support covers Nuxt and"
say "Next only, so nginx is ours to configure. See docs/adr/0002."
say ""
say "The template must exist BEFORE the site, because template edits do not"
say "propagate to sites that already exist."
open_url "https://forge.laravel.com/servers"
step "Open your server, then: Nginx Templates -> New Template."
step "Name it 'tanstack-start'."
step "Paste the contents of deploy/nginx.conf.template, then save."
say ""
note "In that file, point the /media/ alias at the uploads directory you will"
note "use in stage 5. The default is /home/forge/alm-uploads/."
pause "Saved the template?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the site"
say "Now the site itself."
step "Server -> Sites -> New Site."
step "Domain: alm.autos (it will not resolve here yet, which is expected)."
step "Project type: Static HTML / Nuxt.js / Next.js."
step "Package manager: bun."
step "Nginx template: the 'tanstack-start' one from stage 3."
say ""
warn "ENABLE ZERO-DOWNTIME DEPLOYS. This is creation-time only; adding it later"
warn "means deleting and recreating the site."
say ""
step "Under shared paths, add the uploads directory: /home/forge/alm-uploads"
note "Anything written inside releases/ is deleted by the next deploy. Without"
note "this, the client's uploaded photos vanish on the first redeploy."
say ""
step "Connect the repository, branch: feat/tanstack-rebuild (or main once merged)."
pause "Site created with zero-downtime on and the shared path added?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Site environment"
say "Building the environment block you will paste into Forge."
say ""
ask ENQUIRY_FROM_EMAIL "Address notifications are sent FROM (e.g. enquiries@alm.autos):"
ask ENQUIRY_NOTIFY_EMAIL "Address that RECEIVES enquiry notifications:"
write_env DATABASE_URL "postgres://forge:${DB_PASSWORD}@127.0.0.1:5432/forge"
write_env SITE_URL "https://alm.autos"
write_env VITE_SITE_URL "https://alm.autos"
write_env UPLOADS_DIR "/home/forge/alm-uploads"
write_env PORT "3000"
write_env NODE_ENV "production"
write_env ENQUIRY_FROM_EMAIL "$ENQUIRY_FROM_EMAIL"
write_env ENQUIRY_NOTIFY_EMAIL "$ENQUIRY_NOTIFY_EMAIL"
say ""
say "RESEND_API_KEY arrives in stage 10 and the Umami values in stage 11."
step "Site -> Environment. Paste everything from $ENV_FILE, then save."
warn "PORT must match the {{PORT}} nginx substitutes, and nothing restarts the"
warn "Node process when you change a variable here. You restart it by hand."
pause "Environment saved?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "The Node process"
say "Forge will not keep a Nitro app alive on its own; Supervisor does."
step "Site -> Background Processes (or Server -> Daemons) -> New."
step "Command:   node .output/server/index.mjs"
step "Directory: the site's current path, e.g. /home/forge/alm.autos/current"
step "User: forge.  Processes: 1."
step "Create it, then find the daemon's numeric id in the list."
say ""
ask DAEMON_ID "Paste the daemon id (digits only):"
write_env DAEMON_ID "$DAEMON_ID"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Deploy script and first deploy"
say "The deploy script must restart that daemon, after activating the release."
say ""
step "Site -> Deployment -> edit the deploy script."
step "Paste deploy/forge-deploy.sh, replacing daemon-12345 with daemon-${DAEMON_ID}."
say ""
warn "Never put a long-running start command in the deploy script. It blocks"
warn "forever and the deploy hits Forge's 10-minute timeout. The daemon from"
warn "stage 6 is what runs the server."
say ""
step "Deploy Now. Watch the log."
note "The first deploy installs dependencies and builds; give it a few minutes."
note "A 502 immediately afterwards is normal until the daemon is running."
pause "Deploy finished green?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "First run"
say "One-time setup over SSH, from the site's current directory."
say ""
step "ssh forge@${SERVER_IP}"
step "cd /home/forge/alm.autos/current"
say ""
say "Then, in order:"
step "bun run db:migrate       # create the tables"
step "bun run images:build     # legacy photos -> UPLOADS_DIR"
step "bun run db:seed          # 25 vehicles; skips any that already exist"
step "bun run admin:create -- owner@alm.autos"
say ""
note "admin:create reads the password from stdin so it stays out of shell"
note "history. Use a long one: it is the only account, and the only reset flow"
note "is re-running that command."
say ""
step "Finally: sudo supervisorctl restart daemon-${DAEMON_ID}:*"
pause "All four commands succeeded?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify before touching DNS"
say "Forge gives every site a free *.on-forge.com domain. Use it to check"
say "everything works while alm.autos is still safely on GitHub Pages."
say ""
step "Site -> Domains. Copy the on-forge.com address."
ask PREVIEW_DOMAIN "Paste the full preview URL (https://...):"
write_env PREVIEW_DOMAIN "$PREVIEW_DOMAIN"
open_url "$PREVIEW_DOMAIN"
say ""
say "Check, in this order:"
step "The homepage loads and car photos appear (photos prove /media and uploads)."
step "/en/cars lists 25 cars with prices."
step "/sq/cars is in Albanian."
step "/admin redirects to /admin/login, and you can log in."
step "In the admin, open a car and upload a photo; confirm it appears."
step "/sitemap.xml lists cars; /robots.txt disallows /admin."
say ""
warn "If photos are missing, the uploads path or the /media/ nginx alias is wrong."
warn "Fix it now. After the DNS switch this is a live outage, not a rehearsal."
say ""
if ! confirm "Does everything above work?"; then
  warn "Stop here. Nothing public has changed; alm.autos is still on Pages."
  exit 1
fi

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Email"
say "Enquiries are the product, so they must not land in spam. Hetzner IPs are"
say "widely greylisted, which is why this uses Resend rather than local mail."
open_url "https://resend.com/domains"
step "Add the domain alm.autos."
step "Resend shows SPF and DKIM records. Add them at your DNS provider now."
note "These are safe to add before the cutover; they do not affect the website."
step "Wait for Resend to verify the domain."
open_url "https://resend.com/api-keys"
step "Create an API key with send permission."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
write_env RESEND_API_KEY "$RESEND_API_KEY"
step "Add RESEND_API_KEY to the site environment in Forge and save."
step "Restart the daemon so it picks the value up."
say ""
note "Until this is set, the enquiry form refuses submissions rather than"
note "silently losing a lead. That is deliberate."
pause "Resend verified and the key saved?"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "Analytics"
say "Umami, self-hosted at /stats on this same origin, cookieless."
say ""
note "Same origin is load-bearing: the privacy page promises no third-party"
note "request and no cookie banner, and the app refuses a remote script URL."
say ""
if confirm "Set up analytics now? (it can wait until after the cutover)"; then
  step "ssh forge@${SERVER_IP}"
  step "Install Docker:  curl -fsSL https://get.docker.com | sh"
  step "Create its database:  psql -U forge -c 'CREATE DATABASE umami;'"
  step "Copy deploy/umami/docker-compose.yml to /home/forge/umami/."
  step "Write /home/forge/umami/.env with UMAMI_DATABASE_URL and UMAMI_APP_SECRET."
  note "UMAMI_APP_SECRET: openssl rand -base64 32"
  step "docker compose up -d"
  step "Add the /stats/ block from deploy/umami/nginx-snippet.conf to the site nginx."
  step "Open /stats and log in with admin / umami."
  warn "Change that password immediately. It is a published default."
  step "Add the website in Umami and copy its Website ID."
  ask VITE_UMAMI_WEBSITE_ID "Paste the Umami website id:"
  write_env VITE_UMAMI_SRC "/stats/script"
  write_env VITE_UMAMI_WEBSITE_ID "$VITE_UMAMI_WEBSITE_ID"
  step "Add both to the Forge environment, then DEPLOY AGAIN."
  warn "These are build-time values. Saving them in Forge alone does nothing"
  warn "until the site is rebuilt."
else
  SKIPPED+=("Umami analytics: see deploy/umami/README.md")
  note "Skipped. The site works fine without it and emits no script at all."
fi
pause "Ready for the cutover?"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "The cutover"
warn "This is the visible step. Everything before it was reversible."
say ""
say "Yesterday's job, if you have not done it:"
step "Lower the TTL on the alm.autos A/CNAME records to 300 seconds."
note "If the TTL is still hours long, a rollback takes hours to take effect."
say ""
if ! confirm "Has the TTL been at 300s for a few hours already?"; then
  warn "Lower it now and come back later today or tomorrow. Re-running this"
  warn "wizard is safe; it remembers what you have entered."
  exit 1
fi
say ""
say "Now, at your DNS provider:"
step "Remove the GitHub Pages records for alm.autos (its A records or CNAME)."
step "Add an A record: alm.autos -> ${SERVER_IP}"
step "Add an A record: www.alm.autos -> ${SERVER_IP} (or a CNAME to alm.autos)"
say ""
warn "Do NOT delete the gh-pages setup or the repository's Pages configuration."
warn "That is the rollback, and it costs nothing to leave in place."
say ""
step "Back in Forge: Site -> Domains -> SSL -> Let's Encrypt."
step "Choose DNS-01 validation and add the CNAME it shows you."
note "DNS-01 works behind proxies and needs no inbound port 80. Leave that"
note "CNAME in place forever, or renewals fail silently."
pause "DNS switched and certificate issued?"

# ── 13 ────────────────────────────────────────────────────────────────────
stage "After the cutover"
open_url "https://alm.autos"
say "Check on the real domain:"
step "https://alm.autos loads over HTTPS with no certificate warning."
step "A car page shows photos."
step "Send yourself a test enquiry and confirm the email arrives."
step "/admin/login works and you can log in."
say ""
say "One more thing, so the privacy promise stays true:"
step "Add the retention cron on the box:"
note "  0 3 * * * cd /home/forge/alm.autos/current && bun run db:purge-enquiries"
note "Enquiries are personal data and the privacy page promises they are"
note "deleted after 12 months. Without this cron, that promise is false."
say ""
warn "ROLLBACK, if something is badly wrong:"
note "  Point the alm.autos DNS back at GitHub Pages. With a 300s TTL that"
note "  takes minutes. The old site is still in legacy/ and Pages is still"
note "  configured. Do not debug a live outage: roll back, then debug."
say ""
note "Leave GitHub Pages in place for about a week before cleaning it up."
pause "All checks passed?"

finish
