/**
 * Downloads the web fonts so the site serves them itself.
 *
 * Loading them from fonts.googleapis.com sends every visitor's IP to Google on
 * every page, which the privacy page explicitly says does not happen. Cookieless
 * was the whole reason we skipped a consent banner, so the fonts have to be
 * local. Run once; the output is committed.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const OUT_DIR = resolve(ROOT, "public/fonts");

// A modern UA is what makes Google return woff2 rather than ttf.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,500;9..144,600&family=Inter:wght@400;500;600&display=swap";

// Albanian needs ë and ç, which live in latin; latin-ext is kept for safety.
const WANTED_SUBSETS = new Set(["latin", "latin-ext"]);

const css = await (await fetch(CSS_URL, { headers: { "user-agent": UA } })).text();

await mkdir(OUT_DIR, { recursive: true });

const blocks = css.split("@font-face").slice(1);
const rewritten: string[] = [];

// Both families are variable fonts, so Google serves one file for every weight.
// Downloading it per weight would triple the payload for identical bytes.
const filenameByUrl = new Map<string, string>();

for (const block of blocks) {
  const subset = block.match(/\/\*\s*([a-z-]+)\s*\*\//)?.[1];
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  if (!subset || !family || !url || !WANTED_SUBSETS.has(subset)) continue;

  const weight = block.match(/font-weight:\s*([^;]+);/)?.[1]?.trim() ?? "400";
  const style = block.match(/font-style:\s*([^;]+);/)?.[1]?.trim() ?? "normal";
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();

  let filename = filenameByUrl.get(url);
  if (!filename) {
    filename = `${family.toLowerCase().replace(/\s+/g, "-")}-${subset}.woff2`;
    const bytes = await (await fetch(url, { headers: { "user-agent": UA } })).arrayBuffer();
    await writeFile(resolve(OUT_DIR, filename), new Uint8Array(bytes));
    filenameByUrl.set(url, filename);
  }

  rewritten.push(
    [
      "@font-face {",
      `  font-family: "${family}";`,
      `  font-style: ${style};`,
      `  font-weight: ${weight};`,
      "  font-display: swap;",
      `  src: url("/fonts/${filename}") format("woff2");`,
      range ? `  unicode-range: ${range};` : null,
      "}",
    ]
      .filter(Boolean)
      .join("\n"),
  );
}

await writeFile(
  resolve(ROOT, "src/styles/fonts.css"),
  `/* Generated by scripts/fetch-fonts.ts. Self-hosted so no visitor data reaches Google. */\n\n${rewritten.join("\n\n")}\n`,
);

process.stdout.write(
  `${filenameByUrl.size} font files -> public/fonts, ${rewritten.length} faces\n`,
);
