/**
 * The admin is Albanian only — one person uses it, and he is Albanian. The
 * public site is the bilingual part.
 *
 * Reviewed by the client before launch, like the rest of the Albanian copy.
 */
export const t = {
  brand: "ALM Autos",
  admin: "Paneli",
  nav: {
    vehicles: "Makinat",
    seasons: "Sezonet",
    enquiries: "Kërkesat",
    settings: "Kontaktet",
    viewSite: "Shiko faqen",
    logout: "Dil",
  },
  login: {
    title: "Hyr në panel",
    email: "Email",
    password: "Fjalëkalimi",
    submit: "Hyr",
    working: "Duke hyrë…",
    invalid: "Email-i ose fjalëkalimi nuk është i saktë.",
    throttled: "Shumë përpjekje. Prit 15 minuta dhe provo përsëri.",
    failed: "Diçka shkoi keq. Provo përsëri.",
  },
  vehicles: {
    title: "Makinat",
    add: "Shto makinë",
    empty: "Nuk ka asnjë makinë ende.",
    published: "Publikuar",
    hidden: "Fshehur",
    retired: "Hequr",
    featured: "Në krye",
    noPhoto: "Pa foto",
    moveUp: "Ngjit lart",
    moveDown: "Zbrit poshtë",
    order: "Radha ruhet automatikisht.",
  },
  vehicle: {
    newTitle: "Makinë e re",
    editTitle: "Ndrysho makinën",
    specs: "Specifikimet",
    days: "ditë",
    model: "Modeli",
    modelHint: "P.sh. Volkswagen Golf",
    year: "Viti",
    slug: "Adresa në internet",
    slugHint: "Pjesa pas /cars/. Nuk ndryshohet pasi makina publikohet.",
    slugLocked: "Adresa nuk mund të ndryshohet sepse makina është e publikuar.",
    transmission: "Marshi",
    fuel: "Karburanti",
    bodyType: "Lloji",
    seats: "Vende",
    doors: "Dyer",
    airConditioning: "Kondicioner",
    status: "Statusi",
    featured: "Shfaqe në krye të listës",
    descriptionSq: "Përshkrimi (shqip)",
    descriptionEn: "Përshkrimi (anglisht)",
    prices: "Çmimet për ditë",
    pricesHint: "Në euro. Lëri njësoj nëse nuk bën zbritje për qira të gjata.",
    photos: "Fotot",
    photosHint: "Foto e parë shfaqet në listë. Mund të ngarkosh disa njëherësh.",
    upload: "Ngarko foto",
    uploading: "Duke ngarkuar…",
    deletePhoto: "Fshi foton",
    makeFirst: "Bëje të parën",
    save: "Ruaj",
    saving: "Duke ruajtur…",
    saved: "U ruajt.",
    delete: "Fshi makinën",
    deleteConfirm:
      "Kjo fshin makinën dhe të gjitha fotot e saj përgjithmonë. Zakonisht është më mirë ta ndryshosh statusin në “Hequr”. Të vazhdohet?",
    unknown: "Nuk e di",
    back: "Të gjitha makinat",
  },
  seasons: {
    title: "Sezonet",
    intro:
      "Sezonet vlejnë për të gjitha makinat dhe përsëriten çdo vit. Çdo ditë e qirasë llogaritet me sezonin e vet.",
    add: "Shto sezon",
    empty: "Nuk ka sezone. Çmimet bazë vlejnë gjithë vitin.",
    name: "Emri",
    from: "Nga",
    to: "Deri",
    multiplier: "Shumëzuesi",
    multiplierHint: "1.35 do të thotë 35% më shtrenjtë. 0.9 do të thotë 10% zbritje.",
    example: "Shembull: 30 €/ditë bëhet",
    save: "Ruaj",
    delete: "Fshi",
    deleteConfirm: "Të fshihet ky sezon?",
    overlapNote: "Nëse dy sezone mbulojnë të njëjtën ditë, fiton ai më lart në listë.",
  },
  enquiries: {
    title: "Kërkesat",
    intro: "Kërkesat fshihen automatikisht pas 12 muajsh.",
    empty: "Nuk ka kërkesa ende.",
    exportCsv: "Shkarko CSV",
    handled: "Trajtuar",
    markHandled: "Shëno si të trajtuar",
    markUnhandled: "Kthe si të patrajtuar",
    delete: "Fshi",
    deleteConfirm: "Të fshihet kjo kërkesë?",
    car: "Makina",
    dates: "Datat",
    noCar: "Pa makinë të caktuar",
    call: "Telefono",
    whatsapp: "WhatsApp",
  },
  settings: {
    title: "Kontaktet",
    intro: "Këto shfaqen në të gjithë faqen.",
    phone: "Telefoni",
    whatsapp: "Numri i WhatsApp",
    whatsappHint: "Vetëm shifra, me kodin e shtetit. P.sh. 355685658888",
    email: "Email",
    addressLine: "Adresa",
    city: "Qyteti",
    instagram: "Instagram (lidhja)",
    facebook: "Facebook (lidhja)",
    mapsQuery: "Kërkimi në Google Maps",
    hours: "Orari",
    hoursHint: "P.sh. Hën–Shtu 08:00–20:00",
    save: "Ruaj",
    saving: "Duke ruajtur…",
    saved: "U ruajt.",
  },
  status: {
    published: "Publikuar",
    hidden: "Fshehur",
    retired: "Hequr",
  },
  transmission: { manual: "Manual", automatic: "Automatik" },
  fuel: { petrol: "Benzinë", diesel: "Naftë", lpg: "Gaz", hybrid: "Hibrid", electric: "Elektrik" },
  bodyType: {
    hatchback: "Hatchback",
    sedan: "Sedan",
    suv: "SUV",
    van: "Furgon",
    pickup: "Pick-up",
    convertible: "Kabriolet",
  },
  months: [
    "Janar",
    "Shkurt",
    "Mars",
    "Prill",
    "Maj",
    "Qershor",
    "Korrik",
    "Gusht",
    "Shtator",
    "Tetor",
    "Nëntor",
    "Dhjetor",
  ],
  genericError: "Diçka shkoi keq. Provo përsëri.",
};
