/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminSeasonsRouteImport } from './routes/admin/seasons'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as MediaFilenameRouteImport } from './routes/media/$filename'
import { Route as LangCarsIndexRouteImport } from './routes/$lang/cars/index'
import { Route as LangCarsSlugRouteImport } from './routes/$lang/cars/$slug'
import { Route as AdminVehiclesIdRouteImport } from './routes/admin/vehicles/$id'
import { Route as AdminVehiclesNewRouteImport } from './routes/admin/vehicles/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MediaFilenameRoute = MediaFilenameRouteImport.update({
  id: '/media/$filename',
  path: '/media/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const LangCarsIndexRoute = LangCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCarsSlugRoute = LangCarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const AdminVehiclesIdRoute = AdminVehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminVehiclesNewRoute = AdminVehiclesNewRouteImport.update({
  id: '/vehicles/new',
  path: '/vehicles/new',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/media/$filename': typeof MediaFilenameRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/cars/$slug': typeof LangCarsSlugRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/admin/vehicles/new': typeof AdminVehiclesNewRoute
  '/$lang/cars/': typeof LangCarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/media/$filename': typeof MediaFilenameRoute
  '/$lang': typeof LangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$lang/cars/$slug': typeof LangCarsSlugRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/admin/vehicles/new': typeof AdminVehiclesNewRoute
  '/$lang/cars': typeof LangCarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/media/$filename': typeof MediaFilenameRoute
  '/$lang/': typeof LangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$lang/cars/$slug': typeof LangCarsSlugRoute
  '/admin/vehicles/$id': typeof AdminVehiclesIdRoute
  '/admin/vehicles/new': typeof AdminVehiclesNewRoute
  '/$lang/cars/': typeof LangCarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/privacy'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/seasons'
    | '/admin/settings'
    | '/media/$filename'
    | '/$lang/'
    | '/admin/'
    | '/$lang/cars/$slug'
    | '/admin/vehicles/$id'
    | '/admin/vehicles/new'
    | '/$lang/cars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/privacy'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/seasons'
    | '/admin/settings'
    | '/media/$filename'
    | '/$lang'
    | '/admin'
    | '/$lang/cars/$slug'
    | '/admin/vehicles/$id'
    | '/admin/vehicles/new'
    | '/$lang/cars'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/admin'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/privacy'
    | '/admin/enquiries'
    | '/admin/login'
    | '/admin/profile'
    | '/admin/seasons'
    | '/admin/settings'
    | '/media/$filename'
    | '/$lang/'
    | '/admin/'
    | '/$lang/cars/$slug'
    | '/admin/vehicles/$id'
    | '/admin/vehicles/new'
    | '/$lang/cars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MediaFilenameRoute: typeof MediaFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/media/$filename': {
      id: '/media/$filename'
      path: '/media/$filename'
      fullPath: '/media/$filename'
      preLoaderRoute: typeof MediaFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/cars/': {
      id: '/$lang/cars/'
      path: '/cars'
      fullPath: '/$lang/cars/'
      preLoaderRoute: typeof LangCarsIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/cars/$slug': {
      id: '/$lang/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/$lang/cars/$slug'
      preLoaderRoute: typeof LangCarsSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/admin/vehicles/$id': {
      id: '/admin/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/admin/vehicles/$id'
      preLoaderRoute: typeof AdminVehiclesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/vehicles/new': {
      id: '/admin/vehicles/new'
      path: '/vehicles/new'
      fullPath: '/admin/vehicles/new'
      preLoaderRoute: typeof AdminVehiclesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangIndexRoute: typeof LangIndexRoute
  LangCarsSlugRoute: typeof LangCarsSlugRoute
  LangCarsIndexRoute: typeof LangCarsIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangIndexRoute: LangIndexRoute,
  LangCarsSlugRoute: LangCarsSlugRoute,
  LangCarsIndexRoute: LangCarsIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSeasonsRoute: typeof AdminSeasonsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVehiclesIdRoute: typeof AdminVehiclesIdRoute
  AdminVehiclesNewRoute: typeof AdminVehiclesNewRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSeasonsRoute: AdminSeasonsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminVehiclesIdRoute: AdminVehiclesIdRoute,
  AdminVehiclesNewRoute: AdminVehiclesNewRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MediaFilenameRoute: MediaFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
